In [1]:
# Importing the NumPy library
import numpy as np

In [2]:
# Using functions
display(np.sqrt(9))

3.0

In [3]:
display(np.square(3))

9

In [4]:
display(np.maximum(2,3))

3

In [5]:
display(np.absolute(-10))

10

In [6]:
display(np.sign(111))

1

In [7]:
# Creating arrays
a1 = np.array([1,2,3,4])
display(isinstance(a1,np.ndarray))

True

In [8]:
display(a1.shape)
display(a1)

(4,)

array([1, 2, 3, 4])

In [9]:
a2 = np.array([[1,2,3],[4,5,6]])
display(a2.shape)
display(a2)

(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
display(a2.dtype)

dtype('int32')

In [11]:
a3 = np.arange(27).reshape(3,3,3)
display(a3.shape)
display(a3)

(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [12]:
a4 = np.zeros((5,2),dtype=bool)
display(a4)

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [13]:
a5 = np.empty(10)
display(a5)

array([1.56482917e-311, 1.77863633e-322, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 9.51724022e-043, 7.48418026e-067, 7.11817627e-091,
       3.15625580e-033, 8.48636268e-315])

In [14]:
# The datatypes; int, float, bool, object, may be inferred or declared
a6 = np.array([[1,2],[3,4],[5]],dtype=object)
display(a6.shape)
display(a6)

(3,)

array([list([1, 2]), list([3, 4]), list([5])], dtype=object)

In [15]:
display(a6.dtype)

dtype('O')

In [16]:
a7 = np.array([1,2,3.14])
display(a7.shape)
display(a7.dtype)

(3,)

dtype('float64')

In [17]:
# Accessing arrays
a = np.array([1,2,3,4])
display(a[0:4])

array([1, 2, 3, 4])

In [ ]:
display(a[1:3])

In [ ]:
display(a[:-1])

In [ ]:
display(a[2:])

In [ ]:
display(a[[1,1]])

In [ ]:
display(a[[True,False,False,True]])

In [19]:
b = np.arange(12).reshape(4,3)
display(b)
display(b[3,2])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

11

In [20]:
display(b[1:3,:2])

array([[3, 4],
       [6, 7]])

In [ ]:
display(b[[0,3],[0,2]])

In [21]:
# Assigning values to array elements

a[0] += 1
display(a)

array([2, 2, 3, 4])

In [22]:
a[2:] = np.array([5,6])
display(a)

array([2, 2, 5, 6])

In [23]:
a[:2] = [3,4]
display(a)

array([3, 4, 5, 6])

In [24]:
b = a[1:3]
display(b)

array([4, 5])

In [25]:
b[0] = 3
display(b)
display(a)

array([3, 5])

array([3, 3, 5, 6])

In [26]:
c = a.copy()
c[1] = 7
display(c)
display(a)

array([3, 7, 5, 6])

array([3, 3, 5, 6])

In [27]:
# Operations involving arrays
a = np.array([1,2,3])
display(np.square(a))

array([1, 4, 9], dtype=int32)

In [28]:
display(np.sign(a))

array([1, 1, 1])

In [29]:
# Operations involving multiple arrays of same size
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b
display(c)

array([5, 7, 9])

In [35]:
# Operations involving operands of different size (broadcasting);
# works when differing dimension size equals 1 for one operand
a = np.array([1,2])
b = np.array([4,5,6])
#c = a+b

In [36]:
d = 5*b
display(d)

array([20, 25, 30])

In [37]:
e = b > 5
display(e)

array([False, False,  True])

In [38]:
f = np.array([[1,2],[3,4]])
g = a+f
display(g)

array([[2, 4],
       [4, 6]])

In [39]:
h = np.array([[1],[2]])
i = np.array([1,2])
j = h-i
display(j)

array([[ 0, -1],
       [ 1,  0]])

In [41]:
# Operating on multiple array elements with apply_along_axis
a = np.arange(15).reshape(5,3)
display(a)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [42]:
display(np.apply_along_axis(lambda x: np.sum(x),0,a))

array([30, 35, 40])

In [43]:
def f(x):
    return np.sum(x)
display(np.apply_along_axis(f,1,a))

array([ 3, 12, 21, 30, 39])

In [44]:
display(np.apply_along_axis(np.sum,1,a))

array([ 3, 12, 21, 30, 39])

In [45]:
# Finding the position of the maximum value with argmax
a = (np.arange(15)*2).reshape(5,3)
display(np.argmax(a))
display(a)

14

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [46]:
display(np.argmax(a,0))

array([4, 4, 4], dtype=int64)

In [47]:
display(np.argmax(a,1))

array([2, 2, 2, 2, 2], dtype=int64)

In [48]:
# Representing missing values by (the float) np.nan
a = np.array([1,2,3,4],dtype=float)
a[2] = np.nan
display(a)

array([ 1.,  2., nan,  4.])

In [49]:
# The following results in error:
# b = np.array([1,2,3,4])
# b[2] = np.nan

In [50]:
c = np.array([True,np.nan,False,False])
display(c)
display(c.dtype)

array([ 1., nan,  0.,  0.])

dtype('float64')

In [51]:
display(np.nan == np.nan)

False

In [52]:
display(np.isnan(np.nan))

True

In [53]:
display(np.nan is np.nan)

True

In [54]:
# Counting with missing values
display(np.sum(np.array([1,2,np.nan,4])))

nan

In [55]:
display(np.nansum(np.array([1,2,np.nan,4])))

7.0

In [56]:
display(np.nanprod(np.array([1,2,np.nan,4])))

8.0

In [57]:
display(np.nanmin(np.array([1,2,np.nan,4])))

1.0

In [58]:
display(np.nanmax(np.array([1,2,np.nan,4])))

4.0

In [59]:
display(np.nanmean(np.array([1,2,np.nan,4])))

2.3333333333333335

In [60]:
# Importing the pandas library
import pandas as pd

In [61]:
# Creating DataFrames
values = np.arange(15).reshape(5,3)
df1 = pd.DataFrame(values,columns=["A","B","C"])
display(df1)

A   B   C
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14

In [62]:
df2 = pd.DataFrame(values,list("abcde"),list("ABC"))
display(df2)

A   B   C
a   0   1   2
b   3   4   5
c   6   7   8
d   9  10  11
e  12  13  14

In [63]:
# Accessing DataFrames
display(df1["B"])

0     1
1     4
2     7
3    10
4    13
Name: B, dtype: int32

In [64]:
display(df1.B)

0     1
1     4
2     7
3    10
4    13
Name: B, dtype: int32

In [65]:
display(isinstance(df1["B"],pd.Series))

True

In [66]:
display(df1["B"].values)

array([ 1,  4,  7, 10, 13])

In [67]:
display(df1["B"].dtype)

dtype('int32')

In [68]:
display(df1["B"][1])

4

In [69]:
display(df1.loc[1:3,["B","C"]])

B   C
1   4   5
2   7   8
3  10  11

In [70]:
display(df1.iloc[1:4,1:])

B   C
1   4   5
2   7   8
3  10  11

In [71]:
display(df1.iloc[1:3])

A  B  C
1  3  4  5
2  6  7  8

In [72]:
display(df1.iloc[:,1:])

B   C
0   1   2
1   4   5
2   7   8
3  10  11
4  13  14

In [73]:
display(df2.loc[:,["A","B"]].iloc[0:3])

A  B
a  0  1
b  3  4
c  6  7

In [74]:
display(df2.loc["a":"c",["A","B"]])

A  B
a  0  1
b  3  4
c  6  7

In [75]:
display(df2.loc[[True,True,False,False,False],[True,False,True]])

A  C
a  0  2
b  3  5

In [76]:
display(df2.iloc[[True,True,False,False,False],[True,False,True]])

A  C
a  0  2
b  3  5

In [77]:
display(df2[[True,True,False,False,False]])

A  B  C
a  0  1  2
b  3  4  5

In [78]:
display(df2["B"]["b"])

4

In [79]:
display(df2.loc["a",["C","B"]])

C    2
B    1
Name: a, dtype: int32

In [80]:
display(df2.loc["a":"d"])

A   B   C
a  0   1   2
b  3   4   5
c  6   7   8
d  9  10  11

In [81]:
display(df2.iloc[0:4])

A   B   C
a  0   1   2
b  3   4   5
c  6   7   8
d  9  10  11

In [82]:
display(df2.at["a","A"])

0

In [83]:
display(df2.iat[0,0])

0

In [84]:
# Accessing DataFrames through boolean indexing
display(df1[[True,False,True,False,True]])

A   B   C
0   0   1   2
2   6   7   8
4  12  13  14

In [85]:
display(df1[df1["B"] % 2 == 0])
display(df1["B"])

A   B   C
1  3   4   5
3  9  10  11

0     1
1     4
2     7
3    10
4    13
Name: B, dtype: int32

In [86]:
display(df1[df1["C"].isin([5,8,11])])

A   B   C
1  3   4   5
2  6   7   8
3  9  10  11

In [87]:
display(df1[(df1["A"] > 3) & (df1["C"].isin([5,8,11]))])

A   B   C
2  6   7   8
3  9  10  11

In [88]:
# Assigning values to DataFrames
df1["B"] = [True,True,False,False,False]
display(df1["B"].dtype)

dtype('bool')

In [89]:
df1["D"] = np.arange(5,dtype=float)
df1["E"] = 1
df1.loc[1,"A"] = np.nan
df1.loc[2,"B"] = np.nan
display(df1)

A    B   C    D  E
0   0.0  1.0   2  0.0  1
1   NaN  1.0   5  1.0  1
2   6.0  NaN   8  2.0  1
3   9.0  0.0  11  3.0  1
4  12.0  0.0  14  4.0  1

In [90]:
display(df1.isnull().values.any())

True

In [91]:
# Dropping rows and columns in DataFrames
df1.drop(columns=["A","B"],inplace=True)
display(df1)

C    D  E
0   2  0.0  1
1   5  1.0  1
2   8  2.0  1
3  11  3.0  1
4  14  4.0  1

In [92]:
# The following results in error:
# df2 = df1.drop(columns="A")
# but not this:
df2 = df1.drop(columns="A",errors="ignore")
display(df2)

C    D  E
0   2  0.0  1
1   5  1.0  1
2   8  2.0  1
3  11  3.0  1
4  14  4.0  1

In [93]:
df3 = df1.drop(index=[2,3])
display(df3)

C    D  E
0   2  0.0  1
1   5  1.0  1
4  14  4.0  1

In [94]:
# Copying DataFrames
df = df1.copy()

In [95]:
df1.at[0,"D"] = 2.0
display(df1)

C    D  E
0   2  2.0  1
1   5  1.0  1
2   8  2.0  1
3  11  3.0  1
4  14  4.0  1

In [96]:
df.at[0,"D"] = 3.0
display(df)

C    D  E
0   2  3.0  1
1   5  1.0  1
2   8  2.0  1
3  11  3.0  1
4  14  4.0  1

In [97]:
display(df.at[0,"D"] == df1.at[0,"D"])

False

In [98]:
# Concatenating DataFrames
df = pd.DataFrame({"A": list("ababab"), "B":[0,0,0,1,1,1],"C": [10,20,30,40,50,60]})
display(df)

A  B   C
0  a  0  10
1  b  0  20
2  a  0  30
3  b  1  40
4  a  1  50
5  b  1  60

In [99]:
display(pd.concat([df[3:],df[:3]]))

A  B   C
3  b  1  40
4  a  1  50
5  b  1  60
0  a  0  10
1  b  0  20
2  a  0  30

In [100]:
# Merging DataFrames (SQL style)
df1 = pd.DataFrame({"LKey": list("abcdef"),"A":[0,0,0,1,1,1]})
display(df1)

LKey  A
0    a  0
1    b  0
2    c  0
3    d  1
4    e  1
5    f  1

In [101]:
df2 = pd.DataFrame({"RKey": list("fedcba"),"B":[0,0,0,1,1,1]})
display(df2)

RKey  B
0    f  0
1    e  0
2    d  0
3    c  1
4    b  1
5    a  1

In [102]:
display(df1.merge(df2,how="outer",left_on="LKey",right_on="RKey"))

LKey  A RKey  B
0    a  0    a  1
1    b  0    b  1
2    c  0    c  1
3    d  1    d  0
4    e  1    e  0
5    f  1    f  0

In [103]:
# Creating groupings
df = pd.DataFrame({"A": list("ababab"), "B":[0,0,0,1,1,1],"C": [10,20,30,40,50,60]})
display(df)

A  B   C
0  a  0  10
1  b  0  20
2  a  0  30
3  b  1  40
4  a  1  50
5  b  1  60

In [104]:
g = df.groupby("A")
display(g.get_group("a"))

A  B   C
0  a  0  10
2  a  0  30
4  a  1  50

In [105]:
display(g.sum())

B    C
A        
a  1   90
b  2  120

In [106]:
g = df.groupby(["A","B"])
display(g.get_group(("a",0)))

A  B   C
0  a  0  10
2  a  0  30

In [107]:
display(g.size())

A  B
a  0    2
   1    1
b  0    1
   1    2
dtype: int64

In [108]:
# Defining and using categorical values
df = pd.DataFrame({"id":[1,2,3,4,5],"award":["silver", "gold", "silver","silver", "gold"]})
display(df)

id   award
0   1  silver
1   2    gold
2   3  silver
3   4  silver
4   5    gold

In [109]:
df["award"] = df["award"].astype("category")
display(df["award"].cat.categories)

Index(['gold', 'silver'], dtype='object')

In [110]:
df["award"] = df["award"].cat.set_categories(["gold","silver","bronze"])
g = df.groupby("award").size()
display(g)

award
gold      2
silver    3
bronze    0
dtype: int64

In [111]:
display(g.get("iron",0))

0

In [112]:
# Reading and writing to comma-separated text (csv) files
df = pd.DataFrame({"id":[np.nan,2,3,4,5],"grade":[np.nan,"b",np.nan,"c","a"]})
display(df)

id grade
0  NaN   NaN
1  2.0     b
2  3.0   NaN
3  4.0     c
4  5.0     a

In [113]:
df.to_csv("myfile.csv",index=False)
df2 = pd.read_csv("myfile.csv")
display(df2)

id grade
0  NaN   NaN
1  2.0     b
2  3.0   NaN
3  4.0     c
4  5.0     a